### ISSUE TITLE
Is encoding for TC Strings planned for Java Library?

### ISSUE THREAD

**Issue by a-s-rose** [InteractiveAdvertisingBureau/iabtcf-java#10]
Hi,

what are the plans for this library to support encoding/updating a TC String? For some internal use cases we need this functionality in the java library.

If this functionality will be provided - are there any timelines, release plans etc for iabtcf-java library?

Thanks in advance
Antje

**Comment by chrispaterson** [comment]
Hi Antje, as far as plans in relation to timelines – it is really difficult to plan when we don't know what resources are available to help.  Right now this is a community effort by those who would like to see a common implementation amongst companies participating in the TCF.

With that said, [the TypeScript library that this is ported from](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core) does support encoding and it was my full intention that this library would support it as well.  

And as far as release plans, we've been working on trying to get a weekly development release out to maven central.

**Comment by a-s-rose** [comment]
Hi Chris, thank you for answer, this helps clarifying the intention of this library.
