### ISSUE TITLE
Incorrect decoding of ConsentGdprSDK compatible String

### ISSUE THREAD

**Issue by anuragagarwal561994** [InteractiveAdvertisingBureau/iabtcf-java#100]
Library: `com.iabtcf:iabtcf-decoder:2.0.7`

**Expected**
If parsable by ConsentGdprSDK should be parseable by TCF

**Current State**
Method `TCString.getVendorConsent` throws exception

```
@Test
public void decode() {
       TCString decode = TCString.decode("BO1Rve6O17Xz9ABABBEN_R-AAAAwzAA");

        System.out.println(decode.getVersion());
        System.out.println(decode.getDefaultVendorConsent());
        System.out.println(decode.getPurposesConsent());
        System.out.println(decode.getCmpId());
        System.out.println(decode.getVendorListVersion());
        System.out.println(decode.getVendorConsent()); // breaks
}
```

While this works:
```
VendorConsentDecoder.fromBase64String("BO1Rve6O17Xz9ABABBEN_R-AAAAwzAA");
```

**Comment by laktech** [comment]
This looks like an invalid string.

https://acdn.origin.appnexus.net/cmp/docs/#/tools/vendor-cookie-decoder also fails to decode it.

The string is too short and doesn't properly encode the "NumEntries" section of the range section.

**Comment by anuragagarwal561994** [comment]
@laktech https://www.consentstringdecoder.com/ is able to decode this string.
