### ISSUE TITLE
max Vendor Id issue

### ISSUE THREAD

**Issue by fmanoir** [InteractiveAdvertisingBureau/iabtcf-java#101]
I think there is an error in the calculation of max Vendor Id 

For a list of legitimate Interest Vendors 

[legitimateInterestVendorsIds] => Array ( [0] => 11 [1] => 15 [2] => 25 [3] => 32 [4] => 42 [5] => 45 [6] => 52 [7] => 68 [8] => 93 [9] => 114 [10] => 115 [11] => 127 [12] => 164 [13] => 210 [14] => 215 [15] => 226 [16] => 253 [17] => 278 [18] => 498 [19] => 511 ) 

and a list of Vendor

[allowedVendorIds] => Array ( [0] => 10 [1] => 11 [2] => 12 [3] => 15 [4] => 25 [5] => 32 [6] => 36 [7] => 42 [8] => 45 [9] => 50 [10] => 52 [11] => 61 [12] => 66 [13] => 68 [14] => 93 [15] => 114 [16] => 115 [17] => 126 [18] => 127 [19] => 128 [20] => 129 [21] => 130 [22] => 153 [23] => 164 [24] => 192 [25] => 199 [26] => 210 [27] => 213 [28] => 215 [29] => 226 [30] => 228 [31] => 253 [32] => 262 [33] => 272 [34] => 278 [35] => 285 [36] => 315 [37] => 368 [38] => 413 [39] => 498 [40] => 507 [41] => 511 [42] => 512 [43] => 550 [44] => 609 [45] => 639 [46] => 663 [47] => 675 [48] => 681 [49] => 687 [50] => 707 [51] => 711 [52] => 712 )

maxVendorId = 511 instead of 712 

I think the error here : 

 bitWriter.write(new VendorFieldEncoder().add(vendorsConsent).build());
 bitWriter.write(new VendorFieldEncoder().add(vendorLegitimateInterest).build());

instead of having the larger element between the two lists, it gets the max of allowedVendorIds and after the value is overwritten by the max of legitimateInterestVendorsIds

**Comment by fmanoir** [comment]
@laktech ?

**Comment by laktech** [comment]
can you submit a test case that shows your usage of TCStringEncoder and the assertion that's being violated?

**Comment by fmanoir** [comment]
TCStringEncoder 
 = CO2UEN9O2UXjvAsAiBFRAtCsAP_AAH_AAAqIFkAByAIEQSFAIUAAACAAAYAfAAACAEAAAAQIASgBQAAAIBAEECAAAACAAAAAAAAEAAAAAAAgAAAAAAAAAAAAAQCMAAAAABAAAAAAAAACAAAACAAACACCCAAAjAf-AmAAsAB4AGQAQAAqABaADQAIgAXYA5ADmAH8AUgA0gBrgDiAH6ARYA-QB_wAgUAMAiABcAFUhIAYBEAC4AKp

**Comment by laktech** [comment]
I don't know what this is. I can't help you unless you show how you're using TCStringEncoder to generate the consent string and how the resulting TCString violates the specification.

**Comment by fmanoir** [comment]
I didn't understand you?
Did you try to select all IAB vendors then after getting TCString, you attempted to decode it and show the value of maxVendorId ?

**Comment by laktech** [comment]
You need to demonstrate that there is an issue. I'm closing this ticket, please re-open when you're able to demonstrate an issue.
