### ISSUE TITLE
Android compatibility: java.time.Instant is available from API level 26

### ISSUE THREAD

**Issue by JanKn** [InteractiveAdvertisingBureau/iabtcf-java#102]
To increase compatibility with older Android devices library could use Calendar, Date or just long epochMillis.
Library does not seem to do any time zone conversions or make any extensive use of the Instant class.

**Comment by laktech** [comment]
there are no plans to add support for older versions of Android.

**Comment by fmanoir** [comment]
https://stackoverflow.com/questions/36000997/android-n-java8-java-time
