### ISSUE TITLE
Wrong TCF V1 encoding/decoding

### ISSUE THREAD

**Issue by nikoplusx** [InteractiveAdvertisingBureau/iabtcf-java#106]
I am creating a TC V1 string using the encoder like so
```scala
  val hasGivenConsentTcStringV1 = TCStringEncoder.newBuilder()
    .version(1)
    .addAllowedVendors(92)
    .tcfPolicyVersion(1)
    .encode()
```
the result is `BO4yybTO4yybTAAAAAENAAAAAAAAAA`
when I am trying to decode the string though
```scala
com.iabtcf.decoder.TCString.decode("BO4yybTO4yybTAAAAAENAAAAAAAAAA")
```
 I do not get back my configured allowed vendors
```
TCStringV1 [getVersion()=1, getCreated()=2020-08-27T09:58:57.900Z, getLastUpdated()=2020-08-27T09:58:57.900Z, getCmpId()=0, getCmpVersion()=0, getConsentScreen()=0, getConsentLanguage()=EN, getVendorListVersion()=0, getVendorConsent()={}, getDefaultVendorConsent()=false, getPurposesConsent()={}]
```
you can notice that `getVendorConsent()={}` **is empty**. Furthermore, when I am trying to access the TcfPolicyVersion
```
tcString.getTcfPolicyVersion match { ... }
```
I am getting an `Error evaluating method : 'getTcfPolicyVersion': Method threw 'java.lang.UnsupportedOperationException' exception.`

While building I can clearly see that he `allowedVendors` member variable of the `TCStringEncoder` class is appropriately populated. So what is going wrong?

I am not sure if the encoding or the decoding is wrong

**Comment by nikoplusx** [comment]
Ok I just realized what the issue is. In the `TCStringEncoderV1` you completely disregard the `allowedVendors` and `tcfPolicyVersion`
```scala
        public TCStringEncoderV1(TCStringEncoder.Builder builder) {
            if (builder.version != 1) {
                throw new IllegalArgumentException("version must be 1: " + builder.version);
            }
            this.version = builder.version;
            this.created = builder.created;
            this.updated = builder.updated;
            this.cmpId = builder.cmpId;
            this.cmpVersion = builder.cmpVersion;
            this.consentScreen = builder.consentScreen;
            this.consentLanguage = builder.consentLanguage;
            this.vendorListVersion = builder.vendorListVersion;
            this.purposesConsent = builder.purposesConsent.build();
            this.vendorsConsent = builder.vendorConsent.build();
            this.defaultConsent = builder.defaultConsent;
        }
```

Maybe you should do something about this...

**Comment by srinivas81** [comment]
@nikoplusx tcfPolicyVersion and allowedVendors are only supported for TCF V2. They didn't exist for V1. Here is a [link](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#vendor-consent-string-format-) for the V1 specification. The only method that doesn't match the specification in V1 is the "purposesAllowed" which has been renamed as "getPurposesConsent()"  to also match the V2 specification. You can find these notes in the Javadoc. 

If you are satisfied with this answer, please close the issue. Thanks.

**Comment by nikoplusx** [comment]
@srinivas81 From what you can see from my second post I eventually understood why this was failing but it is counterintuitive to provide a common builder for both TCF versions and allowing somebody to use methods only included in TCF2 when this somebody has already started building a TC String using TC version 1. This is a software design flaw. But I will close the issue since this software design flaw does not reflect my initial question. It is another topic. Thanks for your response anyway.
