### ISSUE TITLE
Should not be allowed to use TCF version 2 methods when building v1 TC strings

### ISSUE THREAD

**Issue by nikoplusx** [InteractiveAdvertisingBureau/iabtcf-java#107]
I am creating a TC V1 string using the encoder like so

```scala

  val hasGivenConsentTcStringV1 = TCStringEncoder.newBuilder()
    .version(1)
    .addAllowedVendors(92)
    .tcfPolicyVersion(1)
    .encode()
```
I should not be allowed to use `addAllowedVendors` method since I specified version 1. The user cannot know by heart the entire TCF specification. Either create separate builders for the different version - which you already have - and remove this generic builder class or make it impossible for the user to define `allowedVendors` if the version is 1.

**Comment by laktech** [comment]
thanks for your feedback but this is by design. version 1 is only there for backward compatibly and there is little desire to make this more user-friendly.
