### ISSUE TITLE
Are ranges used for publisher restrictions to ensure smaller output?

### ISSUE THREAD

**Issue by ignazioc** [InteractiveAdvertisingBureau/iabtcf-java#108]
I'm generating a TCF2.0 string with a long list of "publisher restrictions".
For sake of simplicity let's assume I'm adding a publisher restriction for purpose 2 on all the vendors between 1 and 100.

Based on the TCF2.0 documentation [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-are-publisher-restrictions)  should be possible to express this in form of a range.

Looking at the length of the  generated TCString I think that the "single vendorID" approach is used because the length of the TCString  grows linearly with the number of vendors included on the publisher restriction section.

To confirm my hypothesis I executed a test comparing consecutive vendorIDs with scattered vendorID and the resulting length of the TCString was identical, confirming that for consecutive vendor  IDs ranges are not applied.

Can someone confirm this is a current limitation of the SDK ? 

thanks.

**Comment by laktech** [comment]
Hey, thanks for reporting your issue. I'll look into this later today to confirm the behavior. The specifications does allow the ability to encode a range of vendor ids within the publisher restriction section and the intent for this library is to behave in this manner.

**Comment by laktech** [comment]
I verified that the code behaves properly. Can you post some code that shows how you're using it?

**Comment by ignazioc** [comment]
Thanks @laktech! After to your comment I looked into your unit tests and found that I was probably using the SDK in an improper way.

The approach I was using was the following:

```java
    String tcMultipleRestrictions() {
        List<PublisherRestrictionEntry> listOfPublisherRestrictions = new ArrayList<>();

        for (int i = 1; i <= 500; i++) {
            listOfPublisherRestrictions.add(PublisherRestrictionEntry.newBuilder()
                .restrictionType(RestrictionType.REQUIRE_CONSENT)
                .addVendor(i)
                .purposeId(3)
                .build());
        }

        TCStringEncoder.Builder builder = TCStringEncoder.newBuilder(encoderBuilder);
        builder.addPublisherRestrictionEntry(listOfPublisherRestrictions);
        return  builder.encode();
    }
```
And this results in a TC string of `3130` characters.

I now switched to a different approach:

```java
    String tcContinuosIDs() {
        TCStringEncoder.Builder builder = TCStringEncoder.newBuilder(encoderBuilder);

        PublisherRestrictionEntry.Builder pre = PublisherRestrictionEntry.newBuilder()
            .purposeId(3)
            .restrictionType(RestrictionType.REQUIRE_CONSENT);
        for (int i = 1; i <= 500; i++) {
            pre.addVendor(i);
        }

        builder.addPublisherRestrictionEntry(pre.build());
        return builder.encode();
    }
```

and this results in a 55 chars TC String. 👍
