### ISSUE TITLE
base64 encode bug android 7.x

### ISSUE THREAD

**Issue by notmani** [InteractiveAdvertisingBureau/iabtcf-java#109]
On android 7.x
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    bytes= java.util.Base64.getUrlDecoder().decode(base64UrlEncodedString);
}
else
{
    bytes = android.util.Base64.decode(base64UrlEncodedString,android.util.Base64.DEFAULT);
}`

there is space "+", "/" on encoded value

`09-03 17:30:15.052 11224 11444 W SCSLibrary: TCF string "CO5KncEO5KncEAsAnBFRA1CsAP/AAH/AAAqIFjgByAIEQSFAIUAAACAAAYAfAAACAEAAAAQIASgB
09-03 17:30:15.052 11224 11444 W SCSLibrary: QAAAIBAEECAAAACAAAAAAAAEAAAAAAAgAAAAAAAAAAAAAQCMAAAAABAAAAAAAAACAAAACAAACACC
09-03 17:30:15.052 11224 11444 W SCSLibrary: CAAAiA/8BIABYADwAMgAgABUADQAIgAXQA5gB/AFIANIAa4A4gB+gEWAPkAf8AUFADAIgAXABVIS
09-03 17:30:15.052 11224 11444 W SCSLibrary: AGARAAuACqQ0AEAAIiACAAEVABAACA==
09-03 17:30:15.052 11224 11444 W SCSLibrary: .ZwAAAAAAAAA=
09-03 17:30:15.052 11224 11444 W SCSLibrary:     "  is invalid and will not be sent! An valid IAB consent string must be encoded in base64url without padding.`

**Comment by laktech** [comment]
It's unclear what you're reporting here. Can you re-open the ticket with a description of the issue, steps to reproduce, expected and actual results?
