### ISSUE TITLE
Updating Java Sources with Bugfixes, Refactorings etc from iabtcf-es

### ISSUE THREAD

**Issue by a-s-rose** [InteractiveAdvertisingBureau/iabtcf-java#11]
Hi,

last weekend I checked out the iabtcf-java project. My intention was to get the already fixed bugs from iabtcf-es also fixed in this library. 

But before doing that I think we may have to do some similar refactorings as already done in iabctf-es, it will be easier after that to cleanup the bugs in iabtcf-java.

Antje

**Comment by chrispaterson** [comment]
Yes!  This library was ported from a much earlier point in time before I refactored the encoder in the es library.  If anyone is interested in refactoring, please let me know and I can jump on a call or whatever we need to walk through the refactor.

**Comment by wittjill** [comment]
@a-s-rose  we are meeting on Friday morning, 8am PT to discuss work streams on the java library. Email me at jill@iabtechlab.com if you are interested in joining.
