### ISSUE TITLE
Unable to decode specific TCF V1 consent string

### ISSUE THREAD

**Issue by AChekroun** [InteractiveAdvertisingBureau/iabtcf-java#110]
Hello,

I'm getting **ByteParseException** while extracting vendorIds with the following consent string : 

> BO5a1L7O5a1L7AAABBENC2-AAAAtHAA

Whereas, I don't have any issue with the following : 

> BON517aON517aAAABAENAA4AAAAApAA

--------

Here is the error illustrated : 

`
        TCString.decode("BO5a1L7O5a1L7AAABBENC2-AAAAtHAA").getVendorConsent();
`

Stacktrace : 

	com.iabtcf.exceptions.ByteParseException: read 3 bytes at index 21 out of bounds for buffer length 23

	at com.iabtcf.utils.BitReader.ensureReadable(BitReader.java:75)
	at com.iabtcf.utils.BitReader.readBits12(BitReader.java:220)
	at com.iabtcf.decoder.TCStringV2.vendorIdsFromRange(TCStringV2.java:175)
	at com.iabtcf.decoder.TCStringV1.fillVendorsV1(TCStringV1.java:202)
	at com.iabtcf.decoder.TCStringV1.getVendorConsent(TCStringV1.java:102)

I am using **com.iabtcf:iabtcf-decoder:2.0.7**

Thanks for your time

**Comment by laktech** [comment]
Looks like you have an invalid string, this doesn't look like a problem with the library.  Feel free to re-open if this tool is able to parse it: https://acdn.origin.appnexus.net/cmp/docs/#/tools/vendor-cookie-decoder

**Comment by AChekroun** [comment]
Hello @laktech 

Somehow, I am able to deserialize this consent string using : https://www.consentstringdecoder.com
