### ISSUE TITLE
Issue with TCF V1 consent String Decoding

### ISSUE THREAD

**Issue by anuragagarwal561994** [InteractiveAdvertisingBureau/iabtcf-java#112]
Some issues have been reported where few V1 strings are not parseable in the current version of the library.
https://github.com/InteractiveAdvertisingBureau/iabtcf-java/issues/110
https://github.com/InteractiveAdvertisingBureau/iabtcf-java/issues/100

As quoted in both these examples, that it doesn't work with https://acdn.origin.appnexus.net/cmp/docs/#/tools/vendor-cookie-decoder

But on contrary both these examples are parseable at https://www.consentstringdecoder.com/
Also I checked for one of them (which is my earlier issue), but it was parseable by ConsentGdprSDK.

I have examples for more such strings.

Are we missing something here?

**Comment by laktech** [comment]
This library doesn't claim to parse invalid strings. Those tickets you reference are such examples. Regarding #110, the error message says that the string is 23 bytes long. This is an insufficient number of bytes to represent a valid string.

**Comment by anuragagarwal561994** [comment]
@laktech So what I am not trying to understand here is, how are these strings parseable at https://www.consentstringdecoder.com/ and using the ConsentGdprSDK library?
iabtcf-java is an extension to ConsentGdprSDK if I am not wrong right?

**Comment by laktech** [comment]
I don't know anything about the site that you reference. iabtcf-java is an implementation of an encoder and decoder for v1.1 and v2 tcf string defined here https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework

The string BO5a1L7O5a1L7AAABBENC2-AAAAtHAA is encoded with range encoding and there just isn't enough bits available to represent the required fields. This is why this library fails to parse the vendor consent field for the string.

**Comment by anuragagarwal561994** [comment]
@laktech I think I got the issue what we are facing:

So when I am doing:
`TCString.decode("BO1uoTyO4F42RABABBEN_X-AAAAyjAA");`

No exception is being thrown at this time, but some bytes are being parsed although wrong and stored in the object.

Now when I am calling the methods let us say `getVersion()` or something, I am getting valid responses since those bytes are valid.

But when I am doing operations such as `getVendorConsent()` / `toString()`, the rest of the bytes are being parsed on the go and then the method breaks. So ideally when at the first place, while decoding the string, an exception should have been thrown, but since it is kind of a lazy evaluation we are winding up with an exception.

Is there a way currently in the library where one can check if the string is valid? If not is it feasible to implement? A better practice is usually is to not wait for the exception to be thrown, but rather check beforehand the validity of the input, since throwing and catching an exception can be heavy operation at large scale.

**Comment by laktech** [comment]
You can call TCString#hashCode to force evaluate all the fields.
