### ISSUE TITLE
Allowing range encoding for publisher restrictions

### ISSUE THREAD

**Issue by srinivas81** [InteractiveAdvertisingBureau/iabtcf-java#117]
There is a use case where we have a publisher restriction for purpose 3, 4, and 5 as Restricted for consent only for all the vendors. It would be nice to represent this as a range instead of list of vendor ids in order to save on size of the tcf string.

**Comment by laktech** [comment]
can you demonstrate that this is the behavior?

**Comment by srinivas81** [comment]
While you using TCStringEncoder builder to add publisher restrictions [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/develop/iabtcf-encoder/src/main/java/com/iabtcf/encoder/TCStringEncoder.java#L658), the class [PublisherRestrictionEntry](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/f2b5573f692ee77b163e55bcbc9ea06812d15de9/iabtcf-encoder/src/main/java/com/iabtcf/encoder/PublisherRestrictionEntry.java#L29) only allows an IntIterable for vendor list. 

Looking at how the signals are encoded [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/f2b5573f692ee77b163e55bcbc9ea06812d15de9/iabtcf-encoder/src/main/java/com/iabtcf/encoder/TCStringEncoder.java#L294), it looks like range encoding is always set to false. 

If you look at VendorConsent encoding [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/f2b5573f692ee77b163e55bcbc9ea06812d15de9/iabtcf-encoder/src/main/java/com/iabtcf/encoder/TCStringEncoder.java#L283), it looks like we try to figure out programmatically, whether to choose range or bit encoding based on size. 

Is it possible to have this behavior for PublisherRestrictions also?  The one problem I see is this line [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/f2b5573f692ee77b163e55bcbc9ea06812d15de9/iabtcf-encoder/src/main/java/com/iabtcf/encoder/TCStringEncoder.java#L286), where we need to determine the number of publisher restrictions, but if we could provide an interface where the application can enforce range vs bit encoding for publisher restrictions, that will be great.

**Comment by srinivas81** [comment]
I think this issue is invalid. It is working as expected.
