### ISSUE TITLE
Publisher restrictions from an existing string doesn't get copied over in the Encoder 

### ISSUE THREAD

**Issue by srinivas81** [InteractiveAdvertisingBureau/iabtcf-java#118]
```
@Test
public void testTemp() {
    String iab = "CO9ZBNoO9ZBNoAOACAENAnCsAP_AAH_AACiQFvNR6RBUJWjjMCAZg7BAAQQLIBADAAwAhAQIAAAAQIAEoBgGKEEQnBUgAAAACAAgAAYAAAAkFCAAAQAAAAAAgQIMQECICwBAAJAAgEEQQwAQAARMAgFSEQAAREwAEC0CARAAqAJAhCAAEgRAgAIAEAAgAgAAIQAgAAAAAAAACUAQBFCAAAAgAAAAAAAAQAAEAAAAAAAAAAAAAAAAAAIAEAAAABoAAAAAAQCAAAQAIAAACAAAIAAAAAAIAYaAQACoAJkAVQBWAFIANIAcQCbAE7CIBAAKgAmQBVAFYAUgArgBxAJsATsKgDAAqACYAI4AUgA4gE2A";
    TCString tcString = TCString.decode(iab);
    TCStringEncoder.TCStringEncoderV2.Builder tcStringEncoder = TCStringEncoder.newBuilder(tcString);
    assertEquals(iab, tcStringEncoder.encode());
}
```

That assert statement fails, but it should pass. The difference is the publisher restrictions are not getting copied over, from what I have noticed.

**Comment by laktech** [comment]
Why should this pass?

**Comment by srinivas81** [comment]
I guess the issue I am pointing out is that the newBuilder of the encoder is not taking the publisher restrictions into account from an existing string. 

I am proving that using the above test case where Its taking an existing valid tcf v2 string which is being decoded by TCString that is provided in this library and then re-encoded using the TCStringEncoder provided by the library without making any changes, and they don't match up.

**Comment by srinivas81** [comment]
@laktech This is the code fix I am looking for: https://github.com/InteractiveAdvertisingBureau/iabtcf-java/pull/119/files

Please let me know if this seems correct, or by design we are not allowed to copy the publisher restrictions. Thanks.

**Comment by srinivas81** [comment]
@laktech Any updates on the above?
