### ISSUE TITLE
Are there some timelines, release plans etc?

### ISSUE THREAD

**Issue by a-s-rose** [InteractiveAdvertisingBureau/iabtcf-java#12]
Hi,

what are the plans for this library? Is it community driven or are there release plans, timelines etc from IAB (Tech Lab)? If so, could you please tell us when a stable version of this library is planned?

Thanks in advance
Antje

**Comment by chrispaterson** [comment]
I think I answered this in #10

**Comment by a-s-rose** [comment]
Yes, thank you :-)
