### ISSUE TITLE
 cookieMaxAgeSeconds, usesCookies, usesNonCookieAccess these attributes are missing in gvl vendor object

### ISSUE THREAD

**Issue by devendrashewale3** [InteractiveAdvertisingBureau/iabtcf-java#127]
using **iabtcf JavaScript library**  we are calculating cookies expiring time using below attributes gvl **vendor** objects  

` "cookieMaxAgeSeconds": 31536000,
      "usesCookies": true,
      "usesNonCookieAccess": false`

Same attributes we are not able to find out so can you please guide how to use those attributes using java library we have used below gradle version.

`implementation("com.iabtcf:iabtcf-extras:2.0.8")`

**Comment by laktech** [comment]
iabtcf-java/iabtcf-extras/src/main/java/com/iabtcf/extras/gvl/Vendor.java
iabtcf-java/iabtcf-extras-jackson/src/main/java/com/iabtcf/extras/jackson/gvl/Vendor.java
iabtcf-java/iabtcf-extras-jackson/src/test/java/com/iabtcf/extras/jackson/gvl/VendorTest.java

needs to be updated with the new fields
