### ISSUE TITLE
Does the lib support features or special purposes?

### ISSUE THREAD

**Issue by egsgordeev** [InteractiveAdvertisingBureau/iabtcf-java#16]
Greetings!

I'm trying to apply this library for our service but don't fully understand how to work with special purposes or features. Is it even possible with this lib?

Please, share some examples of such appliance if it is possible.
Thank you in advance!

**Comment by chrispaterson** [comment]
Special Purposes and Feature are not represented in the string explicitly so the library does not need to support them.
