### ISSUE TITLE
Validation of cmpVersion

### ISSUE THREAD

**Issue by Synraw** [InteractiveAdvertisingBureau/iabtcf-java#18]
Hi

Is there a reason in particular that there is validation on the cmpVersion?
The docs seem to suggest that it is an internal version of the CMP itself, and not related to the standard or version of TCF being talked about.

TCModel.java `setCmpVersion` validates that the value is `> 1`, which seems a bit strange. Couldn't 1 possibly be the initial "release" version of a CMP?

Later on, `isValid` does a different check: `&& this.cmpVersion != 0`, which seems to contradict the first check again.

Is validating this field really necessary in the first place?

Thanks

**Comment by chrispaterson** [comment]
You're right – 1 is valid.  Anything between 0 and 4095 is technically valid based on the number of bits available to encode.  For phase 1 we're focusing on decoding, but we'll make sure to address this when we get to encoding.
