### ISSUE TITLE
Add tests throughout

### ISSUE THREAD

**Issue by adayNU** [InteractiveAdvertisingBureau/iabtcf-java#35]
I'm not sure how anyone could confidently use this library without any form of testing.

**Comment by chrispaterson** [comment]
Stay tuned!

**Comment by SleimanJneidi** [comment]
Hi @adayNU, we are re-working the implementation with thorough testing.

**Comment by adayNU** [comment]
Great news. Also we have a go implementation that we’d love to replicate the “official” test cases in.

**Comment by laktech** [comment]
closing this ticket as there is not a specific action item. we already follow industry standard testing practices.

**Comment by adayNU** [comment]
@laktech could you point me to these tests?

**Comment by laktech** [comment]
our work is currently being done in the develop branch
