### ISSUE TITLE
Consent string encoder

### ISSUE THREAD

**Issue by HarisMobfox** [InteractiveAdvertisingBureau/iabtcf-java#42]
In [TCF v1.0 library ](https://search.maven.org/artifact/com.conversantmedia.gdpr/consent-string-sdk-java/3.0.2/jar) there was support for creation of consent strings using `VendorConsentBuilder`. 
We would like to switch to only this library but there is no option to construct/encode consent strings.

**Comment by SleimanJneidi** [comment]
Hi @HarisMobfox , thanks for reporting that. We will start working on that.

**Comment by laktech** [comment]
The encoder effort is currently feature complete and awaiting review. The 'publisher-restrictions' branch has the latest changes regarding this effort.

**Comment by laktech** [comment]
This is available in iabtcf-core-2.0.5-alpha.0
