### ISSUE TITLE
iabtcf-scala implementation

### ISSUE THREAD

**Issue by ssledz** [InteractiveAdvertisingBureau/iabtcf-java#48]
Hi,

Before I have noticed @laktech commitment to iabtcf-java I have started project iabtcf-scala

It can be found in the following location https://github.com/ssledz/iabtcf-scala

Based on my perf tests it is about 3 times slower in parsing vendor consent for tcf 2.0 string and 
about 10 times slower in parsing vendor consent for tcf 1.0

I think with the support of the community the perf can be improved so I would like to share my work 

Where can I create a merge request ?

**Comment by laktech** [comment]
Hey @ssledz, thanks for thinking of the community. However, at this time, we're currently only focused on a java implementation.
