### ISSUE TITLE
implement IntIterable#containsAny()

### ISSUE THREAD

**Issue by laktech** [InteractiveAdvertisingBureau/iabtcf-java#50]
IntIterable#containsAny() should return true if any of the ids are present.

**Comment by macfol** [comment]
May I contribute to this one?

**Comment by macfol** [comment]
https://github.com/InteractiveAdvertisingBureau/iabtcf-java/pull/56/files

**Comment by macfol** [comment]
@laktech I guess you can close this one. The PR was merged
