### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by kdarrimajou** [InteractiveAdvertisingBureau/iabtcf-java#62]
Hi,

As mentionned [here](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/issues/21),  do you plan to support Android (java=1.7) in an other repository iabtcf-Android ?

**Comment by laktech** [comment]
we still have time to make the library support java 1.7

**Comment by kdarrimajou** [comment]
The main problem is about Instant class which is not available until Android api level 26.  So if you replace Instant by Date (or timestamp or something else from java 1.7), iabtcf-java will support older Android versions.

**Comment by laktech** [comment]
Does usage of java.util.stream cause problems for Android?

**Comment by kdarrimajou** [comment]
No problem with java.util.stream because it is not exposed to user. The only problem that I see is java.time.Instant. 
I offer my help to test your SDK with an Android project, if you need.

**Comment by laktech** [comment]
Hm, I'm not an android expert but that doesn't make sense. Applying your argument, if Android doesn't support Instant, and I use it in a way that is "not exposed to the user" why would that work?

**Comment by kdarrimajou** [comment]
Like it says [here](https://github.com/coinapult/public/issues/3) or [here](https://developer.android.com/studio/write/java8-support), some configurations in Android project allow us to use java 1.8 library.
But we can't use java 1.8 object in our Android code for some Android level API (under API 26 for Instant).

I cloned iabtcf-encoder project and tested it on an Android project, and it works by replacing Instant by Long (for example).

**Comment by laktech** [comment]
can you test the following code snippet,

` BitSetIntIterable.from(10).toStream();`

**Comment by kdarrimajou** [comment]
You are wright, I can't use java 8 languages API for Android API level under 24. It's not as simple as I thought.

Thanks for your time. I think we can close this issue.

**Comment by laktech** [comment]
can you try this, https://developer.android.com/studio/write/java8-support ? It looks like the way in which you use java8 code in android is you have to recompile it. Have you explored this?

**Comment by kdarrimajou** [comment]
Yes, I have. Recompilation works fine on newest devices (API level 24+), but when I test on old device (API level under 24), I get java.lang.VerifyError on runtime.

**Comment by laktech** [comment]
Do you need to support API level under 24?

**Comment by kdarrimajou** [comment]
Yes, I do.  Device under API 24, represent more than 25%. This not negligible for us.
