### ISSUE TITLE
Purposes enum in V2

### ISSUE THREAD

**Issue by AlexandruGhergut** [InteractiveAdvertisingBureau/iabtcf-java#68]
Hi,

For V1 purposes you have this [enum](https://github.com/InteractiveAdvertisingBureau/iabtcf-java/blob/master/iabtcf-decoder/src/main/java/com/iabtcf/v1/Purpose.java) that helps make the code more readable. Do you plan on adding a similar one for V2 Purposes/Special purposes?

Thanks.

**Comment by laktech** [comment]
This enum needs to be dropped. Purposes are defined and versioned by the GVL and thus is the source of truth for this structure.

**Comment by AlexandruGhergut** [comment]
Thank you. Will close the issue since you're about to remove the V1 enum.
