### ISSUE TITLE
TCF v1 - Publisher consent issue

### ISSUE THREAD

**Issue by HarisMobfox** [InteractiveAdvertisingBureau/iabtcf-java#78]
Library `'com.iabtcf:iabtcf-decoder:2.0.5-alpha.0'`

**Expected**
Publisher consent for TCF v1.0 is correctly decoded and all methods could be used from interface `TCString`

**Current state**
Method `TCString.getVendorConsent` throws exception

**Unit test case**
```java
@Test
public void decodePublisherConsetV1() {
   TCString decode = TCString.decode("BOxgOqAOxgOqAAAABBENC2-AAAAtHAA");

   Assert.assertEquals(decode.getVersion(), 1);
   Assert.assertTrue(decode.getDefaultVendorConsent());
   Assert.assertFalse(decode.getPurposesConsent().isEmpty());
   Assert.assertFalse(decode.getVendorConsent().isEmpty()); // here is thrown Exception
}
```

**Exception**
```
com.iabtcf.exceptions.ByteParseException: read 3 bytes at index 21 out of bounds for buffer length 23
	at com.iabtcf.BitReader.ensureReadable(BitReader.java:72)
	at com.iabtcf.BitReader.readBits12(BitReader.java:217)
	at com.iabtcf.decoder.TCStringV2.vendorIdsFromRange(TCStringV2.java:175)
	at com.iabtcf.decoder.TCStringV1.fillVendorsV1(TCStringV1.java:202)
	at com.iabtcf.decoder.TCStringV1.getVendorConsent(TCStringV1.java:102)
```

**Additional note**
Using [online tool ](http://acdn.origin.appnexus.net/cmp/docs/#/tools/publisher-cookie-decoder) section "Decode Publisher Base64 Cookie Value" consent string `BOxgOqAOxgOqAAAABBENC2-AAAAtHAA` is possible to decode.

**Comment by laktech** [comment]
Thanks for reporting the issue. It appears we don't have support for the "Publisher Purposes Consent String Format" section. This capability can be added.

**Comment by laktech** [comment]
support for decoding this is now in the develop branch and will be in the next release.

**Comment by hitesh1343** [comment]
Library: com.iabtcf:iabtcf-decoder:2.0.6-RC1.0
Is this fix is present in the above library. Because TCString.getVendorConsent method still throwing as mentioned in the issue.
